### ISSUE TITLE
Speed up the visualization

### ISSUE THREAD

**Issue by 0xzhou** [piyo56/3dgan-chainer#2]
Hello, thanks to your nice code for visualization.
I've tried your script to visualiza .binvox files, but during the visualization process, it quite slow to generate one .png, I have a lot of .binvox files, is this common situation? is there a quick alternative?

**Comment by raahii** [comment]
Thank you for your interest in 3dgan-chainer. Certainly, the code uses [3D voxel plot of matplotlib](https://matplotlib.org/3.3.1/gallery/mplot3d/voxels.html)  and it can be slow for a big voxel.

Sorry, I don't know any concrete alternatives. I think it would be better to look for a visualization code which uses a GPU. 

JFYI:
 I have [an another repository for binbox visualization](https://github.com/raahii/simple_voxel_viewer) implemented with javascript. I think it is not also fast enough but try it if you've never used it.
